site_name: Self-Driving Vehicle 
nav:
- Home: index.md
- Hardware: about.md
- Cost: cost.md
- Google Colab: googlecolab.md
- Algorithms: algorithms.md
- FAQs: faqs.md

markdown_extensions:
- pymdownx.tasklist
- attr_list

theme: readthedocs
